/** Auto-generated by scripts/import-works.py — do not edit by hand. */
window.POLESH_WORKS = [
  {
    "id": "sosnovy-bor",
    "type": "residential",
    "custom": false,
    "page": "projects/sosnovy-bor.html",
    "title_ru": "Загородный дом «Сосновый Бор»",
    "title_en": "Country House “Sosnovy Bor”",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "КП «Сосновый Бор»",
    "place_en": "Sosnovy Bor",
    "card_ru": "Загородный дом среди сосен: спокойный свет, дерево и собранный бытовой сценарий.",
    "card_en": "A country house among pines — quiet light, timber and a gathered daily ritual.",
    "images": [
      {
        "src": "images/works/sosnovy-bor/01.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/02.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/03.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/04.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/05.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/06.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/07.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/08.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/09.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/10.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/11.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/12.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/13.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/14.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/15.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/16.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/17.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/18.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/19.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/20.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/21.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/22.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/23.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/24.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/25.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/26.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/27.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/28.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/29.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/30.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/31.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/32.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/33.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/34.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/35.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/36.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/37.jpg",
        "room": null
      },
      {
        "src": "images/works/sosnovy-bor/38.jpg",
        "room": null
      }
    ],
    "cover": "images/works/sosnovy-bor/01.jpg",
    "rooms": []
  },
  {
    "id": "ogni",
    "type": "residential",
    "custom": false,
    "page": "projects/ogni.html",
    "title_ru": "Апартаменты «Огни»",
    "title_en": "Apartments “Ogni”",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "Апартаменты",
    "place_en": "Apartments",
    "card_ru": "Гостиная, спальня и санузел в одной тёплой палитре — городская квартира как тихий отель.",
    "card_en": "Living room, bedroom and bath in one warm palette — a city apartment with hotel calm.",
    "images": [
      {
        "src": "images/works/ogni/01.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/02.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/03.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/04.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/05.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/06.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/07.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/08.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/09.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/10.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/11.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/12.jpg",
        "room": null
      },
      {
        "src": "images/works/ogni/13.jpg",
        "room": null
      }
    ],
    "cover": "images/works/ogni/01.jpg",
    "rooms": []
  },
  {
    "id": "artdeco",
    "type": "residential",
    "custom": true,
    "page": "projects/artdeco.html",
    "title_ru": "Особняк Артдеко",
    "title_en": "Art Deco Mansion",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "Москва",
    "place_en": "Moscow",
    "card_ru": "Столовая, кабинет и ванные — единый жест арт-деко: мрамор, хрусталь и мягкое золото.",
    "card_en": "Dining, study and baths in one Art Deco gesture — marble, crystal and soft gold.",
    "cover": "images/previews/artdeco.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "renaissance",
    "type": "residential",
    "custom": true,
    "page": "projects/renaissance.html",
    "title_ru": "Загородный дом «Ренессанс»",
    "title_en": "Country House “Renaissance”",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "КП «Ренессанс»",
    "place_en": "Renaissance community",
    "card_ru": "Гостиная и ванная в единой палитре: тёплое дерево, камень и спокойный свет.",
    "card_en": "Living room and bath in one palette: warm timber, stone and quiet light.",
    "cover": "images/previews/renaissance.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "kompozitorov",
    "type": "residential",
    "custom": false,
    "page": "projects/kompozitorov.html",
    "title_ru": "Квартира в ЖК «Резиденции композиторов»",
    "title_en": "Residence of Composers Apartment",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "Москва",
    "place_en": "Moscow",
    "card_ru": "Клубный дом: сдержанная геометрия, тактильные поверхности и вечерний свет.",
    "card_en": "A club house apartment — restrained geometry, tactile surfaces and evening light.",
    "images": [
      {
        "src": "images/works/kompozitorov/01.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/02.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/03.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/04.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/05.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/06.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/07.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/08.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/09.jpg",
        "room": null
      },
      {
        "src": "images/works/kompozitorov/10.jpg",
        "room": null
      }
    ],
    "cover": "images/works/kompozitorov/01.jpg",
    "rooms": []
  },
  {
    "id": "zarechnaya",
    "type": "residential",
    "custom": false,
    "page": "projects/zarechnaya.html",
    "title_ru": "Загородный дом «Заречная»",
    "title_en": "Country House “Zarechnaya”",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "КП «Заречная»",
    "place_en": "Zarechnaya",
    "card_ru": "Загородный ритм: широкие проёмы, мягкая мебель и свет, который ведёт через дом.",
    "card_en": "A country rhythm — wide openings, soft furniture and light that leads through the house.",
    "images": [
      {
        "src": "images/works/zarechnaya/01.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/02.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/03.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/04.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/05.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/06.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/07.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/08.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/09.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/10.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/11.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/12.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/13.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/14.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/15.jpg",
        "room": null
      },
      {
        "src": "images/works/zarechnaya/16.jpg",
        "room": null
      }
    ],
    "cover": "images/works/zarechnaya/01.jpg",
    "rooms": []
  },
  {
    "id": "knyazhichi",
    "type": "residential",
    "custom": false,
    "page": "projects/knyazhichi.html",
    "title_ru": "Таунхаус КП «Княжичи»",
    "title_en": "Townhouse “Knyazhichi”",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "КП «Княжичи»",
    "place_en": "Knyazhichi",
    "card_ru": "Таунхаус с собранной вертикалью: лестница, гостиная и приватные этажи как один жест.",
    "card_en": "A townhouse in one vertical gesture — stair, living floor and private levels.",
    "images": [
      {
        "src": "images/works/knyazhichi/01.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/02.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/03.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/04.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/05.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/06.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/07.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/08.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/09.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/10.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/11.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/12.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/13.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/14.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/15.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/16.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/17.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/18.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/19.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/20.jpg",
        "room": null
      },
      {
        "src": "images/works/knyazhichi/21.jpg",
        "room": null
      }
    ],
    "cover": "images/works/knyazhichi/01.jpg",
    "rooms": []
  },
  {
    "id": "petersburg",
    "type": "residential",
    "custom": false,
    "page": "projects/petersburg.html",
    "title_ru": "Таунхаус в Санкт-Петербурге",
    "title_en": "Townhouse in Saint Petersburg",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "Санкт-Петербург",
    "place_en": "Saint Petersburg",
    "card_ru": "Петербургский таунхаус: гостиная, кабинет, детская и спальни в спокойной северной палитре.",
    "card_en": "A Petersburg townhouse — living room, study, nursery and bedrooms in a northern palette.",
    "images": [
      {
        "src": "images/works/petersburg/living/01.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/02.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/03.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/04.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/05.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/06.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/07.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/08.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/09.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/10.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/11.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/living/12.jpg",
        "room": "living"
      },
      {
        "src": "images/works/petersburg/nursery/01.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/02.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/03.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/04.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/05.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/06.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/07.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/08.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/09.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/10.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/11.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/nursery/12.jpg",
        "room": "nursery"
      },
      {
        "src": "images/works/petersburg/study/01.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/02.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/03.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/04.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/05.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/06.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/07.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/study/08.jpg",
        "room": "study"
      },
      {
        "src": "images/works/petersburg/guest-wc/01.jpg",
        "room": "guest-wc"
      },
      {
        "src": "images/works/petersburg/guest-wc/02.jpg",
        "room": "guest-wc"
      },
      {
        "src": "images/works/petersburg/guest-wc/03.jpg",
        "room": "guest-wc"
      },
      {
        "src": "images/works/petersburg/guest-wc/04.jpg",
        "room": "guest-wc"
      },
      {
        "src": "images/works/petersburg/ensuite/01.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/petersburg/ensuite/02.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/petersburg/ensuite/03.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/petersburg/ensuite/04.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/petersburg/ensuite/05.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/petersburg/bedroom-3/01.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/02.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/03.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/04.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/05.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/06.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/bedroom-3/07.jpg",
        "room": "bedroom-3"
      },
      {
        "src": "images/works/petersburg/guest-bed/01.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/02.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/03.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/04.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/05.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/06.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/petersburg/guest-bed/07.jpg",
        "room": "guest-bed"
      }
    ],
    "cover": "images/works/petersburg/living/01.jpg",
    "rooms": [
      {
        "id": "living",
        "title_ru": "Гостиная",
        "title_en": "Living room"
      },
      {
        "id": "nursery",
        "title_ru": "Детская",
        "title_en": "Children’s room"
      },
      {
        "id": "study",
        "title_ru": "Кабинет",
        "title_en": "Study"
      },
      {
        "id": "guest-wc",
        "title_ru": "Гостевой санузел",
        "title_en": "Guest WC"
      },
      {
        "id": "ensuite",
        "title_ru": "Санузел при спальне",
        "title_en": "Ensuite"
      },
      {
        "id": "bedroom-3",
        "title_ru": "Спальня, 3 этаж",
        "title_en": "Third-floor bedroom"
      },
      {
        "id": "guest-bed",
        "title_ru": "Гостевая спальня",
        "title_en": "Guest bedroom"
      }
    ]
  },
  {
    "id": "podmoskovye",
    "type": "residential",
    "custom": false,
    "page": "projects/podmoskovye.html",
    "title_ru": "Загородный дом в Подмосковье",
    "title_en": "Country House in the Moscow Region",
    "tag_ru": "Частный интерьер",
    "tag_en": "Private interior",
    "place_ru": "Подмосковье",
    "place_en": "Moscow Region",
    "card_ru": "Гостиная, прихожая и спальни — загородный дом с ясной планировочной логикой.",
    "card_en": "Living room, entrance and bedrooms — a country house with clear planning logic.",
    "images": [
      {
        "src": "images/works/podmoskovye/living/01.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/02.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/03.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/04.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/05.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/06.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/07.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/08.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/09.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/10.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/11.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/12.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/13.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/14.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/living/15.jpg",
        "room": "living"
      },
      {
        "src": "images/works/podmoskovye/entry/01.jpg",
        "room": "entry"
      },
      {
        "src": "images/works/podmoskovye/entry/02.jpg",
        "room": "entry"
      },
      {
        "src": "images/works/podmoskovye/entry/03.jpg",
        "room": "entry"
      },
      {
        "src": "images/works/podmoskovye/entry/04.jpg",
        "room": "entry"
      },
      {
        "src": "images/works/podmoskovye/entry/05.jpg",
        "room": "entry"
      },
      {
        "src": "images/works/podmoskovye/ensuite/01.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/02.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/03.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/04.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/05.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/06.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/ensuite/07.jpg",
        "room": "ensuite"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/01.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/02.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/03.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/04.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/05.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/06.jpg",
        "room": "guest-bed"
      },
      {
        "src": "images/works/podmoskovye/guest-bed/07.jpg",
        "room": "guest-bed"
      }
    ],
    "cover": "images/works/podmoskovye/living/01.jpg",
    "rooms": [
      {
        "id": "living",
        "title_ru": "Гостиная",
        "title_en": "Living room"
      },
      {
        "id": "entry",
        "title_ru": "Прихожая",
        "title_en": "Entrance"
      },
      {
        "id": "ensuite",
        "title_ru": "Санузел при спальне",
        "title_en": "Ensuite"
      },
      {
        "id": "guest-bed",
        "title_ru": "Гостевая спальня",
        "title_en": "Guest bedroom"
      }
    ]
  },
  {
    "id": "lobby",
    "type": "commercial",
    "custom": true,
    "page": "projects/lobby.html",
    "title_ru": "Лобби бутик-отеля",
    "title_en": "Boutique Hotel Lobby",
    "tag_ru": "Общественное пространство",
    "tag_en": "Public space",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Волнообразный деревянный потолок, живые стены и сценарий встречи гостя.",
    "card_en": "A wave-like timber ceiling, living walls and a guest journey from the door.",
    "cover": "images/previews/lobby.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "hotel-hall",
    "type": "commercial",
    "custom": false,
    "page": "projects/hotel-hall.html",
    "title_ru": "Гостевой холл бутик-отеля",
    "title_en": "Boutique Hotel Guest Hall",
    "tag_ru": "Общественное пространство",
    "tag_en": "Public space",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Промежуточное пространство между лобби и номерами — свет, материал, пауза.",
    "card_en": "The in-between of lobby and rooms — light, material, a pause.",
    "images": [
      {
        "src": "images/works/hotel-hall/01.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/02.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/03.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/04.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/05.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/06.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/07.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/08.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/09.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/10.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/11.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-hall/12.jpg",
        "room": null
      }
    ],
    "cover": "images/works/hotel-hall/01.jpg",
    "rooms": []
  },
  {
    "id": "hotel-floors",
    "type": "commercial",
    "custom": false,
    "page": "projects/hotel-floors.html",
    "title_ru": "Холл 2–4 этажей",
    "title_en": "Floors 2–4 Hall",
    "tag_ru": "Общественное пространство",
    "tag_en": "Public space",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Вертикальные холлы этажей: навигация, камерный свет и повторяющийся ритм.",
    "card_en": "Vertical floor halls — wayfinding, intimate light and a repeating rhythm.",
    "images": [
      {
        "src": "images/works/hotel-floors/01.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/02.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/03.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/04.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/05.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/06.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/07.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/08.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/09.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/10.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/11.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/12.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/13.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/14.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/15.jpg",
        "room": null
      },
      {
        "src": "images/works/hotel-floors/16.jpg",
        "room": null
      }
    ],
    "cover": "images/works/hotel-floors/01.jpg",
    "rooms": []
  },
  {
    "id": "travelers-club",
    "type": "commercial",
    "custom": false,
    "page": "projects/travelers-club.html",
    "title_ru": "Кабинет «Клуб путешественников»",
    "title_en": "Travellers’ Club Study",
    "tag_ru": "Общественное пространство",
    "tag_en": "Public space",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Кабинет-клуб: дерево, книги и атмосфера частного путешествия.",
    "card_en": "A club study — timber, books and the mood of a private journey.",
    "images": [
      {
        "src": "images/works/travelers-club/01.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/02.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/03.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/04.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/05.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/06.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/07.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/08.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/09.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/10.jpg",
        "room": null
      },
      {
        "src": "images/works/travelers-club/11.jpg",
        "room": null
      }
    ],
    "cover": "images/works/travelers-club/01.jpg",
    "rooms": []
  },
  {
    "id": "ostrov",
    "type": "commercial",
    "custom": true,
    "page": "projects/ostrov.html",
    "title_ru": "Номер «Остров»",
    "title_en": "Hotel Ostrov Suite",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Тихая suite-композиция: камень, кожа, ротанг и мягкий свет лесного вида.",
    "card_en": "A quiet suite: stone, leather, rattan and soft forest light.",
    "cover": "images/previews/ostrov.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "sputnik",
    "type": "commercial",
    "custom": true,
    "page": "projects/sputnik.html",
    "title_ru": "Номер «Спутник»",
    "title_en": "Hotel Sputnik Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Ретро-футуризм mid-century: тёплое дерево и культурный жест эпохи.",
    "card_en": "Mid-century retro-futurism: warm timber and a cultural gesture.",
    "cover": "images/previews/sputnik.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "eco",
    "type": "commercial",
    "custom": true,
    "page": "projects/eco.html",
    "title_ru": "Номер «Эко»",
    "title_en": "Hotel Eco Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Биофильный номер: живая стена, натуральные фактуры и графитовый фон.",
    "card_en": "A biophilic room: living wall, natural textures and a graphite backdrop.",
    "cover": "images/previews/eco.jpg",
    "images": [],
    "rooms": []
  },
  {
    "id": "gagarin",
    "type": "commercial",
    "custom": false,
    "page": "projects/gagarin.html",
    "title_ru": "Номер «Гагарин»",
    "title_en": "Hotel Gagarin Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Номер с космической романтикой: свет, круглые мотивы и собранный mid-century жест.",
    "card_en": "A room of space-age romance — light, circular motifs and a mid-century gesture.",
    "images": [
      {
        "src": "images/works/gagarin/01.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/02.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/03.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/04.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/05.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/06.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/07.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/08.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/09.jpg",
        "room": null
      },
      {
        "src": "images/works/gagarin/10.jpg",
        "room": null
      }
    ],
    "cover": "images/works/gagarin/01.jpg",
    "rooms": []
  },
  {
    "id": "orbita",
    "type": "commercial",
    "custom": false,
    "page": "projects/orbita.html",
    "title_ru": "Номер «Орбита»",
    "title_en": "Hotel Orbita Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Орбитальный номер: плотный цвет, характерная мебель и ночной сценарий.",
    "card_en": "An orbital room — dense colour, character furniture and a night-time script.",
    "images": [
      {
        "src": "images/works/orbita/01.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/02.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/03.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/04.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/05.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/06.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/07.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/08.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/09.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/10.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/11.jpg",
        "room": null
      },
      {
        "src": "images/works/orbita/12.jpg",
        "room": null
      }
    ],
    "cover": "images/works/orbita/01.jpg",
    "rooms": []
  },
  {
    "id": "luna",
    "type": "commercial",
    "custom": false,
    "page": "projects/luna.html",
    "title_ru": "Номер «Луна»",
    "title_en": "Hotel Luna Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Лунный номер: серебро, мягкая тень и приглушённый ночной свет.",
    "card_en": "A lunar room — silver, soft shadow and muted night light.",
    "images": [
      {
        "src": "images/works/luna/01.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/02.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/03.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/04.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/05.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/06.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/07.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/08.jpg",
        "room": null
      },
      {
        "src": "images/works/luna/09.jpg",
        "room": null
      }
    ],
    "cover": "images/works/luna/01.jpg",
    "rooms": []
  },
  {
    "id": "indostan",
    "type": "commercial",
    "custom": false,
    "page": "projects/indostan.html",
    "title_ru": "Номер «Индостан»",
    "title_en": "Hotel Indostan Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Индостан: насыщенный орнамент, тёплое дерево и текстиль дальнего путешествия.",
    "card_en": "Indostan — rich ornament, warm timber and textiles of a long journey.",
    "images": [
      {
        "src": "images/works/indostan/01.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/02.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/03.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/04.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/05.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/06.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/07.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/08.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/09.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/10.jpg",
        "room": null
      },
      {
        "src": "images/works/indostan/11.jpg",
        "room": null
      }
    ],
    "cover": "images/works/indostan/01.jpg",
    "rooms": []
  },
  {
    "id": "africa",
    "type": "commercial",
    "custom": false,
    "page": "projects/africa.html",
    "title_ru": "Номер «Африка»",
    "title_en": "Hotel Africa Room",
    "tag_ru": "Гостевой номер",
    "tag_en": "Guest room",
    "place_ru": "Бутик-отель",
    "place_en": "Boutique hotel",
    "card_ru": "Африканский номер: земляные тона, плетёные фактуры и тёплый вечерний свет.",
    "card_en": "An African room — earthen tones, woven textures and warm evening light.",
    "images": [
      {
        "src": "images/works/africa/01.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/02.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/03.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/04.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/05.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/06.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/07.jpg",
        "room": null
      },
      {
        "src": "images/works/africa/08.jpg",
        "room": null
      }
    ],
    "cover": "images/works/africa/01.jpg",
    "rooms": []
  }
];
